models/File.php
<?php

namespace nc\timesheet\models;

use yii\helpers\Inflector;
use yii\web\UploadedFile;
use Yii;
use dektrium\user\models\User;

/**
 * This is the model class for table "{{%files}}".
 *
 * @property integer $id
 * @property string $filename
 * @property string $type
 * @property string $uri
 * @property string $alt
 * @property string $size
 * @property string $description
 * @property string $thumbs
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 */
class File extends \yii\db\ActiveRecord
{
    public $batchUpload;
    public $uploadFile;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%files}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['alt', 'description', 'thumbs'], 'string'],
            [['created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['filename', 'uri'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 255],
            [['size'], 'string', 'max' => 20],
            [['batchUpload'], 'file', 'maxFiles' => 99],
            [['uploadFile'], 'file'],
        ];
    }
    function behaviors(){
        return [
            'timestamp' => \yii\behaviors\TimestampBehavior::className(),
            'blameable' => \yii\behaviors\BlameableBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('nc', 'ID'),
            'filename' => Yii::t('nc', 'Filename'),
            'type' => Yii::t('nc', 'Type'),
            'uri' => Yii::t('nc', 'Uri'),
            'alt' => Yii::t('nc', 'Alt'),
            'size' => Yii::t('nc', 'Size'),
            'description' => Yii::t('nc', 'Description'),
            'thumbs' => Yii::t('nc', 'Thumbs'),
            'created_at' => Yii::t('nc', 'Created At'),
            'updated_at' => Yii::t('nc', 'Updated At'),
            'created_by' => Yii::t('nc', 'Created By'),
            'updated_by' => Yii::t('nc', 'Updated By'),
            'batchUpload' => Yii::t('ecas', 'Files'),
        ];
    }

    function getUpdatedBy(){
      return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }
    function getCreatedBy(){
      return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    /**
     * Handle batchUpload
     */
    function saveUpload(){
      $f = $this->uploadFile;
      if ($f instanceof UploadedFile){
        $prefix = date('Y') . '/' . date('m');
        $path = Yii::getAlias("@webroot/uploads/$prefix");
        @mkdir($path, 0775, true);
        $this->filename = Inflector::slug($f->baseName) . "." . $f->extension;
        $this->uri = $prefix . '/' . $this->filename;
        $this->type = $f->type;
        $suffix = 1;
        while (file_exists($this->getPath())){
                $this->uri = $prefix . '/' . Inflector::slug($f->baseName) . "-$suffix." . $f->extension;
                $suffix ++;
        }
        Yii::info("Save file to " . $this->getPath());
        return $f->saveAs($this->getPath());
      } else Yii::error("uploadFile is not UploadedFile instance");
      return true;
    }
    /**
    * Save batch upload
    */
    function saveBatchUpload(){
        $success = [];
        if (count($this->batchUpload)){
            $prefix = date('Y') . '/' . date('m');
            $path = Yii::getAlias("@webroot/uploads/$prefix" );
            @mkdir($path, 0775, true);
            foreach ($this->batchUpload as $f){
                if ($f instanceof UploadedFile){
                        $file = new static();
                        $file->filename = Inflector::slug($f->baseName) . "." . $f->extension;
                        $file->description = ($this->description) .': '. Inflector::humanize($f->baseName);
                        $file->type = $f->type;
                        $suffix = 1;
                        while (file_exists($file->getPath())){
                                $file->uri = $prefix . '/' . Inflector::slug($f->baseName) . "-$suffix." . $f->extension;
                                $suffix ++;
                        }

                        if ($f->saveAs($file->getPath()) && $file->save()){
                                $success[] = $file->uri;
                        }
                }
            }
        }
        return $success;
    }

    function getPath(){
        return Yii::getAlias("@webroot/uploads/" .  $this->uri);
    }

    function getUrl(){
        return Yii::getAlias("@web/uploads/" . $this->uri);
    }

    function beforeDelete(){
      @unlink($this->path);
      return parent::beforeDelete();
    }

}

models/Timesheet.php
<?php

namespace nc\timesheet\models;
use yii\helpers\ArrayHelper;
use Yii;
use dektrium\user\models\User;

/**
 * This is the model class for table "timesheet".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $approved_by
 * @property string $approved_at
 * @property string $year
 * @property integer $state
 * @property string $comment
 * @property string $status
 */
class Timesheet extends \yii\db\ActiveRecord
{
    // Create Y and W from this date
    public $date;
    // Used in search
    public $dateStart, $dateEnd, $userIDs=[], $approvedByIDs=[];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%timesheet}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['year', 'week', 'user_id', 'state'], 'required'],
            [['user_id', 'approved_by', 'state', 'week'], 'integer'],
            [['approved_at', 'year'], 'safe'],
            [['comment', 'approval_note'], 'string'],
            [['status'], 'string', 'max' => 50],
            [['date', 'dateStart', 'dateEnd'], 'date', 'format' => 'php:Y-m-d'],
            [['user_id'], 'unique', 'targetAttribute' => ['year', 'week', 'user_id']],
	          [['approval_note', 'comment'], 'default', 'value' => ''],
            [['userIDs', 'approvedByIDs'], 'safe'],
        ];
    }
    /**
    * Auto-populate the values from date field
    */
    function setDefaultValues($skipIfSet=true){
      $this->user_id = Yii::$app->user->id;
      $this->date = date('Y-m-d');
      return parent::setDefaultValues($skipIfSet);
    }
    function beforeValidate(){
      if ($this->date){
        $this->year = date('Y', strtotime($this->date));
        $this->week = date('W', strtotime($this->date));
      }
      return parent::beforeValidate();
    }
    function getDateFrom(){
      return date('Y-m-d', strtotime("{$this->year}W{$this->week}"));
    }
    function getDateTo(){
      return date('Y-m-d', strtotime($this->getDateFrom() . " + 6 days"));
    }
    /** Return the title of Timesheet **/
    function getTitle(){
      return $this->year . ' Week #' . $this->week;
    }
    static function state($key){
      return ArrayHelper::getValue(Yii::$app->params['timesheet-status'], $key);
    }

    /**
    * Allow load a timesheet with current year and week
    */
    public static function loadTimesheet($year = null, $week = null, $user_id = null){
      if (!$user_id && Yii::$app->user) $user_id = Yii::$app->user->id;
      if (!$year) $year = date('Y');
      if (!$week) $week = date('W');
      $model = static::find()->where($data = [
        'user_id' => $user_id,
        'week' => $week,
        'year' => $year,
      ])->one();
      if (!$model){
        $data['state'] = 0;
        $model = new static;
        $model->setAttributes($data);
        $model->save();
      }
      return $model;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('nc', 'ID'),
            'user_id' => Yii::t('nc', 'Owner'),
            'approved_by' => Yii::t('nc', 'Approved By'),
            'approved_at' => Yii::t('nc', 'Approval Date'),
            'approval_note' => Yii::t('nc', 'Approval Note'),
            'year' => Yii::t('nc', 'Year'),
            'state' => Yii::t('nc', 'State'),
            'comment' => Yii::t('nc', 'Comment'),
            'status' => Yii::t('nc', 'Status'),
            'dateStart' => Yii::t('nc', 'Start Date'),
            'dateEnd' => Yii::t('nc', 'End Date'),
            'approvedByIDs' => Yii::t('nc', 'Approved By Users'),
            'userIDs' => Yii::t('nc', 'Submit by Users'),
        ];
    }

    function behaviors(){
        return [
            'timestamp' => \yii\behaviors\TimestampBehavior::className(),
            'blameable' => \yii\behaviors\BlameableBehavior::className(),
        ];
    }

    function getEntries(){
      return $this->hasMany(TimeEntry::className(), ['timesheet_id' => 'id']);
    }
    function beforeDelete(){
      TimeEntry::deleteAll(['timesheet_id' => $this->id]);
      return parent::beforeDelete();
    }

    function getOwner(){
      return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    function getApprovedBy(){
      return $this->hasOne(User::className(), ['id' => 'approved_by']);
    }
    function getUpdatedBy(){
      return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }
    function getCreatedBy(){
      return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    function getApprovedByUsernames(){
      return ArrayHelper::map(User::find()->where(['in', 'id', $this->approvedByIDs])->all(), 'id', 'username');
    }
    function getOwnerUsernames(){
      return ArrayHelper::map(User::find()->where(['in', 'id', $this->userIDs])->all(), 'id', 'username');
    }
}

views/dashboard/_files.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
$this->title = "Main Menu";
?>

<div class="panel panel-info">
  <div class="panel-heading">
    <?= Html::a(Yii::t('nc', '{icon} Quick Upload File', ['icon' => Html::icon('file')]), ['batch-upload'], ['class' => 'btn btn-info pull-right']) ?>
    <h4><?= Yii::t('nc', '{icon} My Files', ['icon' => Html::icon('file')]) ?></h4>
  </div>
  <div class="panel-body">
    <?= Html::a(Yii::t('nc', '{icon} New File', ['icon' => Html::icon('file')]), ['upload-file'], ['class' => 'btn btn-default pull-right']) ?>
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'filename',
                'description',
                [ 'class' => 'yii\grid\ActionColumn',
                  'template' => '{download}',
                  'buttons' => [
                    'download' => function ($url, $model, $key) {
                      return Html::a('<span class="glyphicon glyphicon-download"></span>', $model->url, [
                          'title' => Yii::t('nc', 'Download'),
                          'target' => '_blank',
                          'class' => 'linksWithTarget',
                          'data-pjax' => '0',
                      ]);
                    }
                  ]],
              ],
        ]); ?>
    <?php Pjax::end(); ?>
  </div>
</div>

views/dashboard/_leave.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
$this->title = "Main Menu";
?>

<div class="panel panel-danger">
  <div class="panel-heading">
    <?= Html::a(Yii::t('nc', '{icon} New Leave Request', ['icon' => Html::icon('asterisk')]), ['leave-request'], ['class' => 'btn btn-danger pull-right']) ?>
    <h4><?= Yii::t('nc', '{icon} My Leave Request', ['icon' => Html::icon('plane')]) ?></h4>
  </div>
  <div class="panel-body">
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                // 'owner.username:ntext:Owner',
                // 'approved_at',
                'start_date',
                'end_date',
                'note:ntext',
                // 'code',
                // 'all_day',
                // 'number',
                // 'note:ntext',
                // 'approvedBy.username:ntext:Approved By',
                // 'approval_note:ntext',
                // 'approved_at',

                [ 'attribute' => 'state',
                  'value' => function($model){
                    return $model::state($model['state']);
                  }, 'filter' => Yii::$app->params['leave-request-status']
                ],
                [ 'class' => 'yii\grid\ActionColumn',
                  'template' => '{view}',
                  'buttons' => [
                    'view' => function ($url, $model, $key) {
                      return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['leave-request', 'id' => $model->id], [
                          'title' => Yii::t('nc', 'View'),
                      ]);
                    }
                  ]],
              ],
        ]); ?>
    <?php Pjax::end(); ?>

  </div>
</div>

views/dashboard/_meeting.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
$this->title = "Main Menu";
?>

<div class="panel panel-info">
  <div class="panel-heading">
    <?= Html::a(Yii::t('nc', '{icon} Create Meeting', ['icon' => Html::icon('time')]), ['meeting'], ['class' => 'btn btn-primary pull-right']) ?>
    <h4><?= Yii::t('nc', '{icon} My Meeting', ['icon' => Html::icon('briefcase')]) ?></h4>
  </div>
  <div class="panel-body">
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'name',
                'note:ntext',
                // 'owner.username:ntext:Owner',
                'start_date',
                'end_date',
                'all_day:boolean',
                [ 'class' => 'yii\grid\ActionColumn',
                  'template' => '{view}',
                  'buttons' => [
                    'view' => function ($url, $model, $key) {
                      return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['meeting', 'id' => $model->id], [
                          'title' => Yii::t('nc', 'View'),
                      ]);
                    }
                  ],
                ],
              ],
        ]); ?>
    <?php Pjax::end(); ?>
  </div>
</div>

views/dashboard/_time-entry.php
<?php

use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\range\RangeInput;
use nc\timesheet\models\JobCode;



/* @var $this yii\web\View */
/* @var $model nc\timesheet\models\TimeEntry */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="time-entry-form">

    <?php $form = ActiveForm::begin([
      'action' => ['save-time-entry'],
      // 'enableClient  Validation' => false,
      'enableAjaxValidation' => false,
    ]); ?>

    <?= $form->field($model, 'id')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'jobcode_id')->dropDownList(ArrayHelper::map(JobCode::find()->all(), 'id', 'name')) ?>

    <div class="row"><div class="col-md-6">
      <?= $form->field($model, 'date')->widget(DatePicker::className()) ?>
    </div><div class="col-md-6">
      <?= $form->field($model, 'duration')->textInput(['type' => 'number'])?>
      <p class="text-info pull-right"><?= Yii::t('nc', 'Delete this entry by setting <code>duration=0</code>'); ?></p>
    </div></div>
    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group text-right">
        <?= Html::submitButton(Yii::t('nc', '{icon} Save', ['icon' => Html::icon('save')]), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/dashboard/_timesheet.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
$this->title = "Main Menu";
?>

<div class="panel panel-success">
  <div class="panel-heading">
    <?= Html::a(Yii::t('nc', '{icon} Create Timesheet', ['icon' => Html::icon('calendar')]), ['timesheet'], ['class' => 'btn btn-success pull-right']) ?>
    <h4><?= Yii::t('nc', '{icon} My Timesheet', ['icon' => Html::icon('calendar')]) ?></h4>
  </div>
  <div class="panel-body">
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                // 'owner.username:ntext:Owner',
                'approvedBy.username:ntext:Approved By',
                'approved_at',
                'comment:ntext',
                [ 'attribute' => 'state',
                  'value' => function($model){
                    return $model::state($model['state']);
                  }
                ],
                [ 'class' => 'yii\grid\ActionColumn',
                  'template' => '{view}',
                  'buttons' => [
                    'view' => function ($url, $model, $key) {
                      return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['timesheet', 'year' => $model->year, 'week' => $model->week], [
                          'title' => Yii::t('nc', 'View'),
                      ]);
                    }
                  ]],
              ],
        ]); ?>
    <?php Pjax::end(); ?>

  </div>
</div>

views/dashboard/batch-upload.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model nc\timesheet\models\File */
/* @var $form yii\widgets\ActiveForm */
$this->title = Yii::t('nc', 'Batch Upload File');
$this->params['breadcrumbs'][] = ['label' => Yii::t('nc', 'Files'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>

<div class="file-batch">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'batchUpload[]')->widget(FileInput::className(), ['options' => ['multiple' => true]]) ?>

    <?= $form->field($model, 'description')->textArea()->hint('This text will be concatenate with the uploaded file name to create unique description.') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('nc', 'Upload'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/dashboard/timesheet.php
<?php

use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;
use nc\timesheet\models\TimeEntry;

// Notification message 
if ($model->state == 1)
Yii::$app->session->addFlash('info', 'Your timesheet is locked for further processing');
elseif ($model->state == 2)
Yii::$app->session->addFlash('success', 'Your timesheet is already approved');

$events = ArrayHelper::index($model->entries, 'id', 'date');
$summary = []; $total = 0;
foreach ($model->entries as $e) {
  if (!array_key_exists($key = $e->jobCode->name, $summary)) $summary[$key] = 0;
  $summary[$key] += $e->duration; $total += $e->duration;
}
/* @var $this yii\web\View */
/* @var $model nc\timesheet\models\Timesheet */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('nc', 'Timesheet'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="btn-group pull-right" role="group">
    <?= Html::a(Yii::t('nc', '&larr; Previous'), ['', 'year' => date('Y', $lastweek = strtotime($model->dateFrom . ' -1 week')), 'week' => date('W', $lastweek)], ['class' => 'btn btn-default']) ?>
    <?= Html::a(Yii::t('nc', 'This Week'), ['', 'year' => date('Y'), 'week' => date('W')], ['class' => 'btn btn-default']) ?>
    <?= Html::a(Yii::t('nc', 'Next &rarr;'), ['', 'year' => date('Y', $nextweek = strtotime($model->dateFrom . ' +1 week')), 'week' => date('W', $nextweek)], ['class' => 'btn btn-default']) ?>
</div>

<?php if ($model->state > 0): ?>
  <div class="pull-right">
    <?php $form = ActiveForm::begin(['action' => ['export-pdf'], 'enableClientValidation' => false, 'id' => 'pdf-form']); ?>
    <textarea id="html-content" name="content" style="display:none;"></textarea><?php ActiveForm::end(); ?>
    <?= Html::tag('span', Html::icon('save') . ' Export PDF', ['id' => 'export-pdf', 'class' => 'btn btn-primary']); ?>
<?php
$exportPdfUrl = Url::to(['export-pdf']);
$this->registerJs("$(document).ready(function(){
  $('#export-pdf').click(function(e){
    e.preventDefault();
    var content = $('.print-me').html();
    $('#html-content').val(content);
    $('#pdf-form').submit();
  });
});", \yii\web\View::POS_READY); ?>
  </div>
<?php endif; ?>

<div class="print-me">


<h1><small><?= Yii::t('nc', 'Timesheet') ?></small> <?= Html::encode($this->title) ?> <span class="badge"><?= $model::state($model->state); ?></span></h1>

<div class="timesheet-view">
  <div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
      <?php $date = $model->dateFrom;
      $end_date = $model->dateTo;
      $dates = [];
      while ($date <= $end_date){ ?>
        <th><?= date('D d/m', strtotime($date)); ?></th>
      <?php
        $dates[] = $date;
        $date = date('Y-m-d', strtotime("$date + 1 day"));
      }  ?>
      </tr>
    </thead>
    <tbody>
      <tr>
        <?php foreach ($dates as $date): ?>
          <td class="event-panel"><div style="min-height: 200px;">
            <?php foreach (ArrayHelper::getValue($events, $date, []) as $id => $e): ?>
              <?= Html::tag('h5', Yii::t('nc', '{icon} {duration} hr: {jobcode}', [
                'icon' => Html::icon('time'),
                'duration' => $e['duration'],
                'jobcode' => $e->jobCode->name,
                ]),[
                  'style' => ['color' => $e->jobCode->color],
                'title' => $e['description'],
                'class' => 'btn btn-default btn-block event-btn',
                'data-date' => $date,
                'data-id' => $id,
                'data-duration' => $e['duration'],
                'data-description' => $e['description'],
                'data-jobcode_id' => $e['jobcode_id'],
              ]); ?>
            <?php endforeach; ?>
          </div></td>
        <?php endforeach; ?>
      </tr>
    </tbody>
    <?php if ($model->state <= 0): ?>
    <tfoot>
      <tr>
        <?php foreach ($dates as $date): ?>
          <td>
            <?= Html::tag('span', Html::icon('pencil'), [
              'class' => 'btn btn-default btn-block event-new',
              'data-date' => $date,
              'title' => Yii::t('nc', 'Enter new Entry'),
            ]); ?>
          </td>
        <?php endforeach; ?>
      </tr>
    </tfoot>
    <?php endif; ?>
  </table>

</div>
</div>
  <h3><?= Yii::t('nc', 'Time Entries'); ?></h3>
  <?= GridView::widget([
    'dataProvider' => new ArrayDataProvider(['allModels' => $model->entries]),
    'columns' => [
      'date',
      ['attribute' => 'date', 'value' => function($d){ return date('l', strtotime($d->date)); }, 'format' => 'ntext', 'label' => 'Date of Week'],
      'jobCode.name:ntext:Job Code',
      'description:ntext',
      'duration:integer',
    ]

  ]); ?>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading"><?= Yii::t('nc', 'Extra Information') ?></div>
      <div class="panel-body">
    <?php if ($model->state <= 0): ?>
      <?php if ($model->approval_note): ?>
        <p class="text-warning"><?= Yii::t('nc', 'The timesheet is rejected by {mgr} at {date} with following reason:', ['mgr' => ArrayHelper::getValue($model->updatedBy, 'username'), 'date' => date('Y-m-d', $model->updated_at)]); ?></p>
        <blockquote><?= $model->approval_note; ?></blockquote>
      <?php endif; ?>
      <?php $form = ActiveForm::begin(); ?>

      <?= $form->field($model, 'comment')->textarea(['rows' => 4]) ?>

      <?= Html::submitButton(Yii::t('nc', '{icon} Submit For Approval', ['icon' => Html::icon('send')]), ['class' => 'btn btn-warning pull-left', 'name' => $model->formName() . "[state]", 'value' => 1]) ?>

      <?= Html::submitButton(Yii::t('nc', '{icon} Save Draft', ['icon' => Html::icon('save')]), ['class' => 'btn btn-primary pull-right', 'name' => $model->formName() . "[state]", 'value' => 0]) ?>

      <?php ActiveForm::end(); ?>

      <?php Modal::begin([
        'id' => 'time-entry-modal',
        'header' => '<h2 id="time-entry-title">Add / Update Time Entry</h2>',
      ]);

      echo $this->render('_time-entry', ['model' => new TimeEntry()]);

      Modal::end();
      $this->registerJs("
      $(document).ready(function(){
        $('.event-new').click(function(e){
          e.preventDefault();
          $('#timeentry-id').val('');
          $('#timeentry-description').val('');
          $('#timeentry-duration').val('');
          $('#timeentry-date').val(this.dataset.date);
          $('#time-entry-modal').modal();
        });
        $('.event-btn').click(function(e){
          e.preventDefault();
          for (var key in this.dataset){
            $('#timeentry-' + key).val(this.dataset[key]);
          }
          $('#time-entry-modal').modal();
        });
      });", \yii\web\View::POS_READY);
      ?>

    <?php else: ?>
      <blockquote><p><?= $model->comment; ?></p></blockquote>

      <?= DetailView::widget([
          'model' => $model,
          'attributes' => [
              'approvedBy.username:ntext:Approved',
              'approved_at',
              [ 'label' => 'state',
                'value' => ArrayHelper::getValue(Yii::$app->params, "timesheet-status.{$model['state']}")
              ],
              'comment:ntext',
              'status',
          ],
      ]) ?>
    <?php endif; ?>
  </div></div>
</div><div class="col-md-6">
  <h4 class="text-info"><?= Yii::t('nc', 'Total time spent by Job Code'); ?></h4>
  <ul class="summary">
  <?php foreach($summary as $label => $value): ?>
    <li><strong><?= $label ?>:</strong> <span class="pull-right"><?= $value ?> hr</span></li>
  <?php endforeach; ?>
  </ul>
  <hr>
  <ul class=""><li>
  <strong><?= Yii::t('nc', 'Total') ?>:</strong> <span class="pull-right"><?= $total ?> hr</span></li></ul>
</div></div>
</div>
</div>